### PR TITLE
AliYun Log Service target for Logary.

### PR DESCRIPTION
**Pull request by lust4life**
- aliyun log service is a cloud service log product in china :  https://help.aliyun.com/document_detail/48869.html
- use logary target log to aliyun sls 

screenshot for working result :

aliyun-1

image

### CODE REVIEW

**Comment by lust4life** [comment]
checks failed:  seems paket download failed.

@haf  can you release a nuget package for this target after review this pr ?

**Comment by haf** [comment]
Paket bootstrapper feeling low today. Rerunning for second time now after upgrading it.

**Comment by haf** [comment]
Failing with

```
/home/travis/build/logary/logary/src/targets/Logary.Targets.AliYun/Targets_AliYun.fs(137,31): error FS0039: The namespace or module 'Aliyun' is not defined
```

Now. Good failure.

**Comment by lust4life** [comment]
@haf   update paket and fix some conflict, so commit `paket install` change many proj files, maybe skip this commit for reviewing clearly. 

build success , but `paket pack` failed : 
```bash
Paket failed with:
	The file "src/targets/Logary.Targets.AliYun/bin\$(Configuration)\Logary.Targets.AliYun.dll" requested in C:\projects\logary\paket.template does not exist.
```
is anything need me to do for paket ?

**Comment by lust4life** [comment]
@haf  checks are all passed. but because of rebase master branch , commits hash maybe rewrite.

**Comment by haf** [comment]
Thank you! Do you agree to maintain this target?

**Comment by haf** [comment]
Thank you. I'll release tomorrow.

**Comment by lust4life** [comment]
tks

**Comment by haf** [comment]
How about adding the screenshot in this PR to the README?

**Comment by haf** [comment]
Released!

Perhaps add docs below this section? https://github.com/logary/logary#stackdriver-target-alpha-level

**Comment by lust4life** [comment]
ok.

**Pull request merged**
