### PR TITLE
Bugfix/make sql tests work

### PR DESCRIPTION
**Pull request by bradder555**

### CODE REVIEW

**Comment by haf** [comment]
Thank you @bradder555

**Comment by haf** [comment]
Would you be open to helping us maintain the SQL target going forward? It would be **very** appreciated to have someone who uses it, help us maintain it.

**Comment by bradder555** [comment]
Hi Haf, 
I did make a start on getting the mssql target work, but due to time pressures we set up and are using influxdb.

I am still keen to spend some time on this but it'll be outside of work hours

**Comment by haf** [comment]
How fortunate we also support InfluxDB then ;)

**Pull request merged**
