### PR TITLE
Microsoft Azure Application Insights target for Logary.

### PR DESCRIPTION
**Pull request by Thorium**
See all the Logary logged messages in Microsoft Application Insights TRACE-events.
Allows more details to use-case #133
For usage example, see `src\targets\Logary.Targets.AppInsights\Script.fsx`

Working:
sample

How should this be released?
@haf are you the one to release targets?
Feel free to add to Nuget if so.
Do you create all the packages as separate Nuget package?

### CODE REVIEW

**Comment by haf** [comment]
Yes, our build script automatically creates packages from the DLLs. Currently the build is failing on Linux, probably due to the FS being case-sensitive, with:

```
Paket failed with:
	The file "src/targets/Logary.Targets.AppInsights/bin/Release/Logary.Targets.AppInsights.xml" requested in /home/travis/build/logary/logary/paket.template does not exist.
rake aborted!
Albacore::CommandFailedError: Command failed with status (1):
  mono tools/paket.exe pack output build/pkg
```

Do you accept to maintain this target, if I add it to the code-base? Maintenance primarily revolves around bumping its dependencies once in a while and porting it when new major version of Logary are released (every other year approximately).

**Comment by Thorium** [comment]
I can maintain.

**Comment by haf** [comment]
Thank you!

**Comment by Thorium** [comment]
And howabout NuGet package release? Do I have to do still something now?

**Comment by haf** [comment]
Tomorrow I'll release it :)

**Pull request merged**
