### PR TITLE
Feature/middleware

### PR DESCRIPTION
**Pull request by whyer**
Now logary actually uses the configured middleware!

### CODE REVIEW

**Comment by haf** [comment]
Nice!

**Comment by haf** [comment]
I was a bit too early here. You tests cause the test runner to hang.

**Comment by haf** [comment]
I've reverted the merge, please resend it

**Comment by whyer** [comment]
I am very sorry but I can not reproduce any hangs on my Windows machines (at home or work). Maybe some differences with mono-implementation on OSX?

Can you point out some code that may be wrong?

**Comment by haf** [comment]
If you resend the PR I've added travis integration.

The only change of the code is the code that sends GetLogger to Registry. I think it may be connected to when the 'run' in the testCase is being called with respect to when the GetLogger message is received by the Registry.

The solution then would be to replace 'run' and have a `job { ... }` around it all which is run at the end of the testCase, returning the values to be tested.

This hasn't been required for any other test though, so if you PR again then we can see what travis says.

**Pull request merged**
