### PR TITLE
Format log messages so that Stackdriver error reporting picks up exceptions

### PR DESCRIPTION
**Pull request by akselsson**
Stackdriver error reporting can automatically pick up errors from log
entries if they are formatted properly:

"When logging error data from App Engine, Kubernetes Engine or Compute
Engine, the only requirement is for the log entry to contain the full
error message and stack trace. It should be logged as a multi-line
textPayload or in the message field of jsonPayload"

"C#: Must be the return value of Exception.ToString()"

https://cloud.google.com/error-reporting/docs/formatting-error-messages

This PR aims to change the formatting of errors to conform with those guidelines. 

Note that I considered using tokeniseExceptions from MessageWriter, but that function outputs a stacktrace that is not equal to Exception.ToString() and thus does not conform to Google's recommendations.

### CODE REVIEW

**Comment by akselsson** [comment]
In the future, we may want to add support for supplying serviceContext.service and serviceContext.version to Stackdriver since service is also a required field. I have, however found that it's sufficient to add an application property to jsonPayload instead, which works for us.

**Comment by haf** [comment]
Thank you @akselsson I'll put out a new release with this change in it!

**Comment by haf** [comment]
Fixes https://github.com/logary/logary/issues/349

**Comment by haf** [comment]
Released as v5-beta.22

**Pull request merged**
