### PR TITLE
Customize log4net codelocation

### LINKED ISSUE #256: format code-location(LocationInformation) in log4net adapter
```fsharp
    let data =
      [ "app_domain",       box evt.Domain
        "thread_principal", box evt.Identity
        "code_location",    box evt.LocationInformation
        "thread_name",      box evt.ThreadName
        "user",             box evt.UserName ]
      |> Map.ofList
```

evt.LocationInformation has an StackFrames property, shall we customize it to a readability string here ? or we should do this job in the target level (find code_location field and format it there) ?

### PR DESCRIPTION
**Pull request by lust4life**
- format code location info to fullinfo string append newline

should close #256 

the result ：
before:
image

after:
image

### CODE REVIEW

**Comment by lust4life** [comment]
@haf  didn't know why travis ci build failed, expecto tests on my machine(windows) is ok.

**Comment by haf** [comment]
Please rebase, to avoid needless merge commits in the PR.

**Comment by haf** [comment]
You've broken a test:

```
[10:42:41 ERR] integration tests (memory only)/logging to log4net logs to logary failed in 00:00:00.4731032. 
```

**Comment by haf** [comment]
Let's rerun the build and see if it works then. It could be a flaky test somewhere.

**Comment by lust4life** [comment]
image
seems weird , why failed only on linux.
ok, next time i will do rebase.

**Comment by lust4life** [comment]
reset to master for testing ci

**Comment by lust4life** [comment]
implement by #219 .

**Pull request closed without merging**
